### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by filtercake** [PolymerElements/polymer-starter-kit#223]
Mac 10.10.3, node 0.12.4, npm 2.10.1

on `npm install`:

```
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/browser-sync requires opn@'^2.0.0' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/opn,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-jshint/node_modules/jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-jshint/node_modules/lodash,
npm WARN unmet dependency which is version 3.9.3
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-minify-html/node_modules/minimize/node_modules/htmlparser2/node_modules/domutils/node_modules/dom-serializer requires domelementtype@'~1.1.1' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-minify-html/node_modules/minimize/node_modules/htmlparser2/node_modules/domelementtype,
npm WARN unmet dependency which is version 1.3.0
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-minify-html/node_modules/minimize/node_modules/htmlparser2/node_modules/domutils/node_modules/dom-serializer requires entities@'~1.1.1' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/gulp-minify-html/node_modules/minimize/node_modules/htmlparser2/node_modules/entities,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/bower requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/bower requires update-notifier@'^0.3.0' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/update-notifier,
npm WARN unmet dependency which is version 0.4.0
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/wd requires async@'~1.0.0' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-parser requires debug@'0.7.4' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/parseuri,
npm WARN unmet dependency which is version 0.0.2
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/request/node_modules/har-validator requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /Users/nyancat/path/to/polymer-1.0-test/node_modules/web-component-tester/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
```

on `gulp serve`

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/filtercake/src/polymer-1.0-test/node_modules/browser-sync/lib/hooks.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

happy to read npm docs if that helps – maybe you can point me to the relevent part(s)?

**Comment by filtercake** [comment]
sorry for openening a ticket – removing node_modules plus `npm cache clean && npm install` did it...
