### ISSUE TITLE
Can't get started on v1.0.3

### ISSUE THREAD

**Issue by aarongable** [PolymerElements/polymer-starter-kit#294]
Below is a shortened console log of what happens when I try to get started with v1.0.3. I haven't confirmed if the same occurs at other versions, but I suspect it does. A full version of the log is available [on pastebin](http://pastebin.com/raw.php?i=WhWBjRTv). The issue is that web-component-tester can't be found, but it's not clear why it can't: the install process seems to proceed just fine for web-component-tester, with the exception that *optional* dependency dtrace-provider fails to install due to relying on node-waf (which no longer exists).

```
/work/personal$ which node
~/local/bin/node

/work/personal$ node --version
v0.12.7

/work/personal$ which npm
~/local/bin/npm

/work/personal$ npm --version
2.13.3

/work/personal$ git clone https://github.com/PolymerElements/polymer-starter-kit
Cloning into 'polymer-starter-kit'...

/work/personal$ cd polymer-starter-kit/

/work/personal/polymer-starter-kit$ git checkout v1.0.3
HEAD is now at e948c97... Add `npm start` script

/work/personal/polymer-starter-kit$ npm install -g gulp bower
~/local/bin/gulp -> ~/local/lib/node_modules/gulp/bin/gulp.js
~/local/bin/bower -> ~/local/lib/node_modules/bower/bin/bower
<snip: no errors>

/work/personal/polymer-starter-kit$ gulp --version
[23:54:27] CLI version 3.9.0

/work/personal/polymer-starter-kit$ bower --version
1.4.1

/work/personal/polymer-starter-kit$ npm install
npm WARN engine launchpad@0.4.7: wanted: {"node":"~0.10"} (current: {"node":"0.12.7","npm":"2.13.3"})
npm WARN optional dep failed, continuing fsevents@0.3.7
<snip>
> dtrace-provider@0.0.9 install /work/personal/polymer-starter-kit/node_modules/web-component-tester/node_modules/wct-local/node_modules/launchpad/node_modules/restify/node_modules/dtrace-provider
> node-waf clean ; node-waf configure build
sh: node-waf: command not found
sh: node-waf: command not found
> sauce-connect-launcher@0.9.3 postinstall /work/personal/polymer-starter-kit/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js
npm WARN optional dep failed, continuing dtrace-provider@0.0.9
<snip>
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "node" "~/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! failed to fetch from registry: https://registry.npmjs.org/vargs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /work/personal/polymer-starter-kit/npm-debug.log

/work/personal/polymer-starter-kit$ bower install
<snip: no errors>

/work/personal/polymer-starter-kit$ gulp serve
module.js:338
    throw err;
    ^
Error: Cannot find module 'web-component-tester'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/work/personal/polymer-starter-kit/gulpfile.js:248:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by vhdirk** [comment]
I'm having the same error.
The issue is that npm install fails for web-component-tester, because one of its dependencies, vargs, cannot be fetched from the npm registry (https://registry.npmjs.org/vargs).

I have yet to find which package relies on vargs, and how to fix this.

**Comment by danyshaanan** [comment]
Seems vargs has reappeared. Check again.

**Comment by addyosmani** [comment]
Confirmed that there was an issue earlier where the package was unavailable. It's since been restored. Tested against master once https://github.com/npm/npm/issues/9168#issuecomment-128034802 was resolved and all appears to be working fine again.
