### ISSUE TITLE
gulp serve doesn't work

### ISSUE THREAD

**Issue by calebeby** [PolymerElements/polymer-starter-kit#297]
When I run `gulp serve`, it returns:
```module.js:338
    throw err;
          ^
Error: Cannot find module 'connect-history-api-fallback'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/caleb/polymer-starter-kit-1.0.2/gulpfile.js:23:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
I have no idea what this means.

**Comment by kenny0202** [comment]
do a "npm install -g connect-history-api-fallback"

it should install the missing module. If other error occurs then install those other modules as well.

**Comment by calebeby** [comment]
Running `npm install -g connect-history-api-fallback`returns
`connect-history-api-fallback@1.1.0 /home/caleb/.nvm/versions/node/v0.12.4/lib/node_modules/connect-history-api-fallback`

`gulp serve` still returns:
```
module.js:338
    throw err;
    ^
Error: Cannot find module 'connect-history-api-fallback'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/caleb/polymer-starter-kit-1.0.2/gulpfile.js:23:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by calebeby** [comment]
Now I ran `npm install --save connect-history-api-fallback`, and it works now. Thanks for getting me on the right track, @kenny0202
