### ISSUE TITLE
Error: Cannot find module 'vinyl' on running 'gulp serve'

### ISSUE THREAD

**Issue by ishandutta2007** [PolymerElements/polymer-starter-kit#399]
npm install -g gulp bower &&  npm install &&  bower install
gulp serve
```
Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dutishan/Documents/node/polymer-starter-kit-1.1.0/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by samccone** [comment]
@ishandutta2007 When you ran npm i did you hit any errors?

**Comment by addyosmani** [comment]
Can you try:

```
$ rm -fr ./node_modules/
$ npm cache clean
$ npm install
```

To see if the dependency issue can be resolved from a freshly cleaned cache?

**Comment by addyosmani** [comment]
friendly ping. Does the above address the issue for you?

**Comment by michaelcrobinson** [comment]
I had a similar issue, and the above resolution provided by @addyosmani solved this and a related issue in one shot.

**Comment by samccone** [comment]
Going to close for now... we can reopen if we get some more details :sparkles:

**Comment by corehook** [comment]
```bash
corehook: /projects/ZeroSap/web-store-angular  # rm -fr ./node_modules/
corehook: /projects/ZeroSap/web-store-angular  # sudo npm cache clean
corehook: /projects/ZeroSap/web-store-angular  # npm install
coffee-script@1.10.0 node_modules/coffee-script

vinyl@1.0.0 node_modules/vinyl
├── clone-stats@0.0.1
├── replace-ext@0.0.1
└── clone@1.0.2

gulp-concat@2.6.0 node_modules/gulp-concat
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── concat-with-sourcemaps@1.0.4 (source-map@0.5.2)

gulp-coffee@2.3.1 node_modules/gulp-coffee
├── merge@1.2.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)

gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
└── vinyl-fs@0.3.14 (graceful-fs@3.0.8, defaults@1.0.3, vinyl@0.4.6, strip-bom@1.0.0, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-util@3.0.7 node_modules/gulp-util
├── array-differ@1.0.0
├── array-uniq@1.0.2
├── fancy-log@1.1.0
├── beeper@1.1.0
├── lodash._reescape@3.0.0
├── lodash._reinterpolate@3.0.0
├── object-assign@3.0.0
├── lodash._reevaluate@3.0.0
├── replace-ext@0.0.1
├── minimist@1.2.0
├── vinyl@0.5.3 (clone-stats@0.0.1, clone@1.0.2)
├── has-gulplog@0.1.0 (sparkles@1.0.0)
├── gulplog@1.0.0 (glogg@1.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── lodash.template@3.6.2 (lodash._basecopy@3.0.1, lodash._basetostring@3.0.1, lodash.restparam@3.6.1, lodash.templatesettings@3.1.0, lodash._isiterateecall@3.0.9, lodash._basevalues@3.0.0, lodash.escape@3.0.0, lodash.keys@3.1.2)
├── multipipe@0.1.2 (duplexer2@0.0.2)
└── dateformat@1.0.11 (get-stdin@5.0.0, meow@3.4.2)

gulp-uglify@1.4.2 node_modules/gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── isobject@2.0.0 (isarray@0.0.1)
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── vinyl-sourcemaps-apply@0.2.0 (source-map@0.5.2)
├── uglify-js@2.5.0 (async@0.2.10, uglify-to-browserify@1.0.2, yargs@3.5.4, source-map@0.5.2)
└── fancy-log@1.1.0 (chalk@1.1.1, dateformat@1.0.11)

gulp-jshint@1.11.2 node_modules/gulp-jshint
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
├── minimatch@2.0.10 (brace-expansion@1.1.1)
├── lodash@3.10.1
└── jshint@2.8.0 (strip-json-comments@1.0.4, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.6, lodash@3.7.0, htmlparser2@3.8.3)
corehook: /projects/ZeroSap/web-store-angular  # ./gulp.sh
module.js:339
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
corehook: /projects/ZeroSap/web-store-angular  #```

**Comment by corehook** [comment]
And have same issue in other project ( that worked few days ago )

```bash
corehook:(master) /projects/ZeroSap/mobile-app-angular  # ./gulp.sh
module.js:339
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by corehook** [comment]
And error when i just run gulp
```bash
corehook: /projects/MyProjects  # gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by gangsthub** [comment]
I'm having this same issue. And yes, there were a "npm ERR! code 1" when running `npm install -g gulp`.

After simply running `npm rebuild node-sass --no-bin-links` I was able to run **gulp** (`gulp.task('default', ['sass']);`)

**Comment by forrestLyman** [comment]
I just ran into this error with both versions of the starter kit. I tried the steps _addyosmani_ described and reinstalled the node modules in each version of the starter kit with no success.

**Comment by ceoaliongroo** [comment]
@forrestLyman try
```bash
npm -g install gulp
```

You can check if is resolved just running:
```bash
gulp -v
```

**Comment by robdodson** [comment]
If you're getting permission errors when you run `npm install -g` make sure your user account has the ability to write to the directory in question (I think it's `/usr/local/bin` if you're on a Mac). It may make sense to give your user account permission to write to that directory instead of doing `sudo npm install -g`. This is a very old npm article but does explain some more thoughts around that. http://howtonode.org/introduction-to-npm
