### ISSUE TITLE
bower ENORESTARGET  No tag found that was able to satisfy ^1.1.0

### ISSUE THREAD

**Issue by rhasson** [PolymerElements/polymer-starter-kit#410]
Did a fresh install of Polymer starter kit 1.1.0 under nodejs 4.1.1 and when I ran bower install I got the following error:
```
 C:\Users\hassonr\My Documents\Personal\Projects\polymer-starter-kit-1.1.0 {git}
{lamb} bower -V install
bower not-cached    git://github.com/Polymer/polymer.git#^1.1.0
bower resolve       git://github.com/Polymer/polymer.git#^1.1.0
bower not-cached    git://github.com/PolymerElements/iron-elements.git#^1.0.0
bower resolve       git://github.com/PolymerElements/iron-elements.git#^1.0.0
bower not-cached    git://github.com/PolymerElements/paper-elements.git#^1.0.1
bower resolve       git://github.com/PolymerElements/paper-elements.git#^1.0.1
bower not-cached    git://github.com/PolymerElements/platinum-elements.git#^1.1.0
bower resolve       git://github.com/PolymerElements/platinum-elements.git#^1.1.0
bower not-cached    git://github.com/PolymerElements/neon-elements.git#^1.0.0
bower resolve       git://github.com/PolymerElements/neon-elements.git#^1.0.0
bower not-cached    git://github.com/visionmedia/page.js.git#~1.6.3
bower resolve       git://github.com/visionmedia/page.js.git#~1.6.3
bower not-cached    git://github.com/PolymerElements/test-fixture.git#^1.0.0
bower resolve       git://github.com/PolymerElements/test-fixture.git#^1.0.0
bower cached        git://github.com/Polymer/web-component-tester.git#3.3.22
bower validate      3.3.22 against git://github.com/Polymer/web-component-tester.git#*
bower ENORESTARGET  No tag found that was able to satisfy ^1.1.0

Additional error details:
No versions found in git://github.com/PolymerElements/platinum-elements.git

Stack trace:
Error: No tag found that was able to satisfy ^1.1.0
    at createError (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\GitResolver.js:144:23
From previous event:
    at GitHubResolver.Resolver.resolve (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\core\resolv
ers\Resolver.js:82:6)
    at PackageRepository._resolve (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\core\PackageRepo
sitory.js:181:21)
    at C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\core\PackageRepository.js:76:29

Console trace:
Error
    at StandardRenderer.error (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRe
nderer.js:82:37)
    at Logger.<anonymous> (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logge
r.js:29:39)
    at C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:45:20
    at _rejected (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\hassonr\AppData\Roaming\npm\node_modules\bower\node_modules\q\
q.js:788:41)
System info:
Bower version: 1.5.3
Node version: 4.1.1
OS: Windows_NT 6.1.7601 x64
```

**Comment by addyosmani** [comment]
Could you try downgrading to Node 0.12.x and test again? We don't yet have official support for Node 4 just yet.

**Comment by rhasson** [comment]
Thanks Addy.  I'll give it a try.
