### ISSUE TITLE
Unable to "gulp serve" PSK 1.1.0 - Windows

### ISSUE THREAD

**Issue by jwuliger** [PolymerElements/polymer-starter-kit#413]
Hello,

I need help please!

I have been able to effortlessly install and run all previous versions of the PSK. I have spent hours now trying to get 1.1.0 to run in my environment. I have done everything I can think of. From googling the error to reviewing all current issues with this version here. Any of the suggested fixes dont work for me.

I have made no code changes and I am running CMD as the Admin.

When I grab a fresh copy of the repository and do the NPM & Bower installs, then run "gulp serve" I get the following error no matter what:

```
C:\FrontEnd\polymer-starter-kit>gulp serve
[09:45:33] Using gulpfile C:\FrontEnd\polymer-starter-kit\gulpfile.js
[09:45:33] Starting 'styles'...
[09:45:33] Starting 'elements'...
[09:45:33] Starting 'images'...
[09:45:33] Finished 'elements' after 249 ms
[09:45:33] styles all files 98 B
[09:45:33] Finished 'styles' after 590 ms
[09:45:34] images all files 35.41 kB
[09:45:34] Finished 'images' after 357 ms
[09:45:34] Starting 'serve'...
[09:45:34] Finished 'serve' after 73 ms
[PSK] Access URLs:
 ------------------------------------
       Local: http://localhost:5000
External: http://xxx.xxx.x.x:5000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://xxx.xxx.x.x:3001
 ------------------------------------
[PSK] Serving files from: .tmp
[PSK] Serving files from: app
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

```
**My Environment:**

- All Required Prerequisites
- Windows 10
- Node.js v4.1.1
- NPM v3.3.4
- Bower v1.5.3

I am also not sure how to get a more detailed stack trace.

What should I do?

Thanks for the help!

**Comment by robdodson** [comment]
Have you tried on Node 0.12. We've been experiencing issues with v4

**Comment by jwuliger** [comment]
No, I will try that and post back! Thanks.

**Comment by jwuliger** [comment]
OK. So using the windows version of NVM, I installed Node v0.12.7. Same error just different line numbers. I am using the same newer version of NPM. Should I also use the older NPM?

**Comment by addyosmani** [comment]
Can you try with `npm install -g npm@2.14.4` and see if that makes a difference?

**Comment by samccone** [comment]
ok I just tested the latest node 4.x.x and latest npm 3.x.x with a clean install of everything on a mac and everything worked like a champ. 

This makes me want to believe that this is a windows issue, @jwuliger can you post the entire error stack from `Error: spawn cmd ENOENT` down

thx a bunch :grapes:

**Comment by jwuliger** [comment]
Thanks for your help you guys. How would I find the stack trace? I am not getting a npm log file generated.

**Comment by jwuliger** [comment]
OK I did a "Gulp" to build then tried to run the dist and was able to get a log file. Here it is:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jwuli\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.6
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\FrontEnd\polymer-starter-kit\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python27\pythonw.exe;C:\Python27\Scripts;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Windows;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Users\jwuli\AppData\Roaming\npm;;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Users\jwuli\AppData\Local\atom\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\MongoDB\Server\3.0\bin;C:\Users\jwuli\AppData\Local\.meteor\
10 verbose lifecycle @~start: CWD: C:\FrontEnd\polymer-starter-kit
11 silly lifecycle @~start: Args: [ '/d /s /c', 'gulp serve' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `gulp serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jwuli\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:817:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd C:\FrontEnd\polymer-starter-kit\dist
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jwuli\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.1.1
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error @ start: `gulp serve`
22 error Exit status 1
23 error Failed at the @ start script 'gulp serve'.
23 error This is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve
23 error You can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jwuliger** [comment]
This has been resolved. I was missing a PATH var to **C:\Windows\System32\** I really need a Mac.. Thanks for your help!!

**Comment by samccone** [comment]
:clap: woot @jwuliger great work debugging
