### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by glenfordwilliams** [PolymerElements/polymer-starter-kit#445]
HI ive been using the starter kit for a while without issues but recently i havent been able to  get pass this error when i run `gulp` to build the project any help would be appreciated
```
06:51:32] Using gulpfile ~\Desktop\coding\stluciaonline\gulpfile.js
[06:51:32] Starting 'clean'...
[06:51:34] Finished 'clean' after 2.61 s
[06:51:34] Starting 'default'...
[06:51:34] Starting 'copy'...
[06:51:35] Starting 'styles'...
[06:51:39] styles all files 2.04 kB
[06:51:39] Finished 'styles' after 4.4 s
[06:51:52] copy all files 13.48 MB
[06:51:52] Finished 'copy' after 18 s
[06:51:52] Starting 'elements'...
[06:51:52] Finished 'elements' after 22 ms
[06:51:52] Starting 'jshint'...
[06:51:54] Starting 'images'...
[06:51:57] Starting 'fonts'...
[06:51:57] Starting 'html'...
[06:52:01] Finished 'fonts' after 4.52 s
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Socket.Writable.end (_stream_writable.js:449:10)
    at Socket.end (net.js:415:31)
    at Through2._transform (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\index.js:64:12)
    at Through2.Transform._read (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Through2.Transform._write (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Through2.Writable.write (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at PassThrough.ondata (C:\Users\Williams\Desktop\coding\stluciaonline\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_readable.js:574:20)
```

**Comment by glenfordwilliams** [comment]
i tried removing the images call from the gulpfile but then i ended up with this error after it was vulcanized 

```
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
elements.vulcanized.html:8587 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a function
3elements.vulcanized.html:8659 Uncaught TypeError: this._desugarBehaviors is not a function
5elements.vulcanized.html:1091 Uncaught TypeError: Cannot read property 'dashToCamelCase' of undefined
2elements.vulcanized.html:3981 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined
elements.vulcanized.html:1091 Uncaught TypeError: Cannot read property 'dashToCamelCase' of undefined
19elements.vulcanized.html:8659 Uncaught TypeError: this._desugarBehaviors is not a function
elements.vulcanized.html:1091 Uncaught TypeError: Cannot read property 'dashToCamelCase' of undefined
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
elements.vulcanized.html:10768 Uncaught TypeError: Cannot read property 'dashToCamelCase' of undefined
app.js:1 Uncaught TypeError: Cannot set property 'scrollTop' of null
2http://localhost:8000/images/touch/chrome-touch-icon-192x192.png Failed to load resource: the server responded with a status of 404 (File not found)````

**Comment by addyosmani** [comment]
Few questions:

* What version of PSK are you using?
* Have you tried running `npm cache clean && npm install` in case one of the dependencies you have didn't correctly resolve due to network issues or something else?

I believe this issue might be https://github.com/Polymer/vulcanize/issues/160 (seems to be a very similar error stack to what you're seeing).

**Comment by addyosmani** [comment]
Due to the age of this issue and not receiving a follow-up, we're closing this one up. If you get a chance to reply to the last comment we'll be more than happy to reopen.
