### ISSUE TITLE
[Windows] Missing Python/VCBuild dependency?

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/polymer-starter-kit#500]
On a fresh install, npm install is unable to install the following module due to the lack of Python install:

```
C:\Wks\github.com\MeTaNoV\BugOver\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Tools\nodejs\node
_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Tools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Tools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Tools\\nodejs\\node.exe" "C:\\Tools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd C:\Wks\github.com\MeTaNoV\BugOver\node_modules\bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.2.1 install C:\Wks\github.com\MeTaNoV\BugOver\node_modules\utf-8-validate
> node-gyp rebuild


C:\Wks\github.com\MeTaNoV\BugOver\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Tools\nodejs\
node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Tools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Tools\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Tools\\nodejs\\node.exe" "C:\\Tools\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd C:\Wks\github.com\MeTaNoV\BugOver\node_modules\utf-8-validate
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
```

**Comment by MeTaNoV** [comment]
Note also that gyp is only supporting up to version 3.0.0, that is one must install the current 2.7.x (x=10 at the time of writing)

**Comment by MeTaNoV** [comment]
Then comes VCBuild.exe dependency! :)

```
MSBUILD : error MSB3428: Impossible de charger le composant Visual C++ "VCBuild.exe". Pour corriger le problème, vous d
evez 1) installer le Kit de développement .NET Framework 2.0 SDK, 2) installer Microsoft Visual Studio 2005 ou 3) ajout
er l'emplacement du composant au chemin d'accès système, s'il est installé ailleurs.  [C:\Wks\github.com\MeTaNoV\BugOve
r\node_modules\utf-8-validate\build\binding.sln]
```

**Comment by samccone** [comment]
welcome to node-gyp and windows :crying_cat_face: 

https://github.com/nodejs/node-gyp/issues/506

good luck :( this is a tricky thing to setup on windows the first time

**Comment by MeTaNoV** [comment]
Thanks for the pointer! :+1:

**Comment by samccone** [comment]
no problem :)

**Comment by samccone** [comment]
xref #504 505

**Comment by MeTaNoV** [comment]
Having ```Python 2.7.10``` and ```Visual Studio 2015``` worked fine without forgetting to ```npm configure --msvs_version=2015``` ! :)
I just wanted to point out that not only ```nodejs```, ```bower``` and ```gulp``` are required to have a working environment for PSK! :)
Thanks for the follow-up!

**Comment by samccone** [comment]
glad it worked out for you @MeTaNoV :)
