### ISSUE TITLE
gulp commands fail - Error: Cannot find module 'core-util-is'

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/polymer-starter-kit#51]
Ran npm install, bower install then gulp serve, tried gulp local:test as well, same result

this is on node 0.12.2

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/google/home/ktiedt/Projects/polymer-starter-kit/node_modules/gulp/node_modules/gulp-util/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by addyosmani** [comment]
Could you share information about what OS you're trying this on?

**Comment by addyosmani** [comment]
Researched. This issue occurs when the `npm install` is abruptly terminated. Please try installing again after deleting your `node_modules` directory. I would attempt this directly: `npm install && bower install && gulp serve`.

**Comment by ktiedt** [comment]
That is interesting, that was definitely the problem. Thanks (would never had guessed npm got stuck in odd states like this, that is a new one for me)

**Comment by addyosmani** [comment]
No worries at all :)

**Comment by ecomuere** [comment]
same problem on ubuntu 15.04. 
node v0.12.7
npm 2.13.3

**Comment by szutzy** [comment]
I meet the same trouble

**Comment by robdodson** [comment]
hm this is a super old issue. @szutzy can you try deleting your `node_modules` folder and running `npm i` again?
