### ISSUE TITLE
Can not find module vinyl on gulp serve

### ISSUE THREAD

**Issue by afzalarsalan** [PolymerElements/polymer-starter-kit#514]
```
# gulp serve
module.js:339
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Already tried the whole shebang with wiping the modules directory, clearing the cache, and reinstalling as in #399 but still have the same problem

Running Linux if that makes a difference

**Comment by afzalarsalan** [comment]
For some reason running ```npm install -g gulp bower``` multiple times seemed to have fixed. The glories of npm

**Comment by scottstanfield** [comment]
@afzalarsalan that worked for me too
