### ISSUE TITLE
Autoprefixer error: "ReferenceError: Promise is not defined"

### ISSUE THREAD

**Issue by fabito** [PolymerElements/polymer-starter-kit#547]
I'm getting the following error when running the gulp default task.
I'm currently using node `v0.10.26`. Is node 4.x  required ?

```
/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
    at DestroyableTransform._transform (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at DestroyableTransform.ondata (/home/fabio/Development/polymer-starter-kit-1.2.0/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:20)
    at DestroyableTransform.EventEmitter.emit (events.js:95:17)
```

**Comment by MeTaNoV** [comment]
definitely!

**Comment by addyosmani** [comment]
Where possible we recommend using Node 4.x and npm3 with PSK. We should definitely highlight this in the docs, but let's wait for a confirm on upgrading solving this particular issue. Could you try upgrading?

**Comment by samccone** [comment]
Yep going to need node 0.12+ here

**Comment by addyosmani** [comment]
Friendly ping @MeTaNoV on the Node comments above :)

**Comment by MeTaNoV** [comment]
@addyosmani me? I am using v5.0.0 for a long time and have no problem whatsoever! :D

**Comment by addyosmani** [comment]
Awesome. @fabito it looks like bumping your Node setup to the latest stable should get this working for you. Can you give that a try and let us know if it addresses the issue?

**Comment by samccone** [comment]
going to close for now, since I think we are pretty confident in the issue. Going to close but we can reopen if this does not resolve it for you @fabito

**Comment by fabito** [comment]
Thanks, I couldn't update  the problematic environment but I tried on a docker container with the latest versions and everything worked fine.

**Comment by samccone** [comment]
:+1: glad to hear
