### ISSUE TITLE
ES2015 support TypeError: Cannot read property 'init'

### ISSUE THREAD

**Issue by Boo-urns** [PolymerElements/polymer-starter-kit#551]
I'm receiving a TypeError when I'm following the ES2015 Support Doc [https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md]

```
TypeError: Cannot read property 'init' of undefined
at Gulp.<anonymous> (/Users/.../gulpfile.js:155:22)
at module.exports (/Users/.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/.../node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/.../node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/.../node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

Line 153 - 163 is: 
```
gulp.task('js', function () {
 return gulp.src(['app/**/*.{js,html}'])
   .pipe($.sourcemaps.init())
   .pipe($.if('*.html', $.crisper())) // Extract JS from .html files
   .pipe($.if('*.js', $.babel({
     presets: ['es2015']
   })))
   .pipe($.sourcemaps.write('.'))
   .pipe(gulp.dest('.tmp/'))
   .pipe(gulp.dest(dist()));
});
```

I started my project with PSK any ideas what I'm missing?

**Comment by Boo-urns** [comment]
I would like to add I did go through the whole doc and added the appropriate changes to my gulpfile.

**Comment by robdodson** [comment]
@Boo-urns can you tell me what's at line 155 of your gulpfile?

**Comment by Boo-urns** [comment]
@robdodson thanks for responding.l I did abandond transpiling to ES5 for the time being on the project since it's still under development.  I tried the updated PSK and seems to be working just fine although I didn't write any JS.

```
// 155 
.pipe($.sourcemaps.init())
```
Perhaps when I was testing it back and forth I forgot to keep the assets updated in the html task?
``` var assets = $.useref.assets(); ```

**Comment by robdodson** [comment]
ok so in that case your error is saying that `sourcemaps` is not defined. Maybe you forgot to install it?

**Comment by Boo-urns** [comment]
Perhaps I don't recall. I think it was too much back and forth and I forgot something trivial.
