### ISSUE TITLE
Gulp serve doesn't lauch the app

### ISSUE THREAD

**Issue by ystreibel** [PolymerElements/polymer-starter-kit#60]
Hi,

I try to install and launch the app.

First, I have an error du to spawn when I type grunt serve.
I fix this by add "try-thread-sleep": "^1.0.0", on package.json
After that, I have this error :
```
[00:50:08] Using gulpfile ~/Projects/polymer-starter-kit/gulpfile.js
[00:50:08] Starting 'styles'...
[00:50:24] Starting 'elements'...
[00:50:24] Starting 'images'...
[00:51:29] 'elements' all files 0 B
[00:51:29] Finished 'elements' after 1.07 min
Unhandled rejection Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
[00:51:29] 'styles' all files 98 B
[00:51:29] Finished 'styles' after 1.35 min
```

**Comment by addyosmani** [comment]
Could you let us know what version of Node you're using?

**Comment by ystreibel** [comment]
```
$ node --version
v0.10.26
```

**Comment by arthurvr** [comment]
> Grunt serve doesn't lauch the app

*Grunt* serve?

**Comment by ystreibel** [comment]
Sorry, I would like to say : 
```
gulp serve
```

**Comment by ystreibel** [comment]
I install the last version of node and npm via https://nodejs.org/ and it works. 
Thanks, for your great jobs !!!
