### ISSUE TITLE
Issue on following the step by step guide on https://www.polymer-project.org/1.0/docs/start/psk/set-up.html

### ISSUE THREAD

**Issue by RiccardoCereghino** [PolymerElements/polymer-starter-kit#790]
### Description
Follow the guide on the polymer-project to set up psk
https://www.polymer-project.org/1.0/docs/start/psk/set-up.html

Follow up to Build and serve step 2 and run

`gulp 
`

### Expected outcome

no errors

### Actual outcome

```
[x@x x]$ gulp
[13:10:09] Using gulpfile ~/x/gulpfile.js
[13:10:09] Starting 'clean'...
[13:10:09] Finished 'clean' after 6.81 ms
[13:10:09] Starting 'default'...
[13:10:09] Starting 'ensureFiles'...
[13:10:09] 'ensureFiles' errored after 280 μs
[13:10:09] Error: Missing Required Files
/home/x/x/.bowerrc Not Found
    at ensureFiles (/home/x/x/tasks/ensure-files.js:24:15)
    at Gulp.<anonymous> (/home/x/x/gulpfile.js:113:3)
    at module.exports (/home/x/x/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/x/x/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/x/x/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/x/x/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/x/x/node_modules/run-sequence/index.js:88:16)
    at runSequence (/home/x/x/node_modules/run-sequence/index.js:99:2)
    at Gulp.<anonymous> (/home/x/x/gulpfile.js:272:3)
    at module.exports (/home/x/x/node_modules/orchestrator/lib/runTask.js:34:7)
[13:10:09] 'default' errored after 3.96 ms
[13:10:09] Error in plugin 'run-sequence'
Message:
    An error occured in task 'ensureFiles'.

```

### Versions
- Polymer Starter Kit: v1.3.0
- gulp: CLI version 3.9.1
- npm: v3.8.3
- node: v5.10.1
- fedora: 23

**Comment by RiccardoCereghino** [comment]
I needed to manually copy and add the .bowerrc file in my PSK directory from this repo, then another error popped up regarding vulcanize which i solved running `bower -i`

**Comment by addyosmani** [comment]
Was the .bowerrc file present in the bundle you downloaded when viewed from a zip/compression app?

**Comment by robdodson** [comment]
@RiccardoCereghino note you'll need to view the bundle in your terminal as the .bowerrc file likely won't show up in your desktop file browser. If you copied the contents of PSK into a new directory you likely didn't copy over the .bowerrc because of this.

**Comment by robdodson** [comment]
This should be fixed in PSK2. We're no longer using a .bowerrc file.
