### ISSUE TITLE
Setup error: jade has been renamed to pug

### ISSUE THREAD

**Issue by dandv** [PolymerElements/polymer-starter-kit#805]
On Windows:

     npm install -g gulp bower && npm install && bower install

Result:

```text
...
 jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

[other errors below]

```
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:821:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\A\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-d8d0aeb8f1d24ec5e2cca7b710f05c84 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine launchpad@0.5.1: wanted: {"node":"^0.12"} (current: {"node":"5.5.0","npm":"3.3.12"})
```

**Comment by samccone** [comment]
These are just warning and are not hard errors :)

**Comment by dandv** [comment]
Correct - they are errors. Just wanted to raise an issue for improving the setup experience for the user by cleaning these up if possible.

**Comment by samccone** [comment]
:+1: fair enough :dancer:
