### ISSUE TITLE
Cannot find module 'orchestrator'

### ISSUE THREAD

**Issue by ShikhaSingh1** [PolymerElements/polymer-starter-kit#851]
### Description
On doing '**gulp serve'** , seeing the following error : 

Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\212421789\Documents\B- Course\Inplementation\polymer-light\polymer-starterkit-light\node_modules\gulp\index.js:4:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by robdodson** [comment]
hm try deleting your node_modules directory and run `npm cache clean` then `npm install` again and try gulp serve one more time. Let me know if that helps
