### ISSUE TITLE
[2.0-preview] Invalid "includeDependencies" in polymer.json

### ISSUE THREAD

**Issue by tony19** [PolymerElements/polymer-starter-kit#961]
### Description
The `2.0-preview` branch's `polymer.json` lists [`webcomponents-lite.min.js`](https://github.com/PolymerElements/polymer-starter-kit/blob/141d2b5/polymer.json#L17) in `includeDependencies` (likely carried over from the `master` branch), which doesn't actually exist in the `webcomponentsjs#v1` branch and thus causes `polymer build` to error out. It seems `polymer.json` was never updated for `2.0-preview`.

### Expected outcome
 * No errors or warnings
 * Produces the `build/` directory with all required files

### Actual outcome
 * Emits warnings (`sourceGlobs` and `includeDependencies` are deprecated keys)
 * Fails with error:
```shell
warn:    "sourceGlobs" config option has been renamed to "sources" and will no longer be supported in future versions
warn:    "includeDependencies" config option has been renamed to "extraDependencies" and will no longer be supported in future versions
info:    Deleting build/ directory...
error:   Uncaught exception: Error: File not found with singular glob: /Users/tony/src/polymer/tony19-polymer-starter-kit/bower_components/webcomponentsjs/webcomponents-lite.min.js
error:   Error: File not found with singular glob: /Users/tony/src/polymer/tony19-polymer-starter-kit/bower_components/webcomponentsjs/webcomponents-lite.min.js
    at Glob.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/index.js:41:11)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/usr/local/lib/node_modules/polymer-cli/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
```

### Live Demo
n/a

### Steps to reproduce

 1. Check out `2.0-preview branch`.
 2. Install bower dependencies with `bower i`.
 3. Run `polymer build`.

### Browsers Affected
n/a

### Environment
 * `2.0-preview` branch
 * macOS Sierra 10.12
 * Node 7.4.0
 * `polymer-cli` 0.18.0-alpha.8

**Comment by robdodson** [comment]
I'm going to remove the 2.0 branch until Polymer releases the 2.0 alpha (ETA sometimes this quarter). The reason is because a lot of the issues that are cropping up now have to do with the fact that 2.0 is still in dev mode so they haven't done things like stage a .min version of webcomponents.js. I'd rather not chase a moving target.
